# ==============================
# APP CONFIGURATION
# ==============================

spring.application.name=backend

# ==============================
# DB CONFIGURATION
# ==============================

spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_db
spring.datasource.username=workflow
spring.datasource.password=workflow

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# JWT CONFIGURATION
# ==============================

jwt.secret=workflow-management-system-super-secure-secret-key-256bit
jwt.expiration=86400000

# ==========================
# MAILTRAP SMTP CONFIG
# ==========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thugofcoding@gmail.com
spring.mail.password=xdsdmjngxjwpcewq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true